initial_pose_x: 0.0
initial_pose_y: 0.0
initial_pose_a: 0.0
odom_alpha1: 0.2
odom_alpha2: 0.1
odom_alpha3: 0.4
odom_alpha4: 0.2
update_min_d: 0.015
update_min_a: 0.0945
min_particles: 100
max_particles: 1000
laser_model_type: likelihood_field_prob
odom_model_type: diff-corrected
use_map_topic: true
selective_resampling: false
