use_inf: true
inf_epsilon: 1.0
concurrency_level: 1
transform_tolerance: 0.01
angle_increment: 0.0087
scan_time: 0.1
min_height: -0.0
max_height: 0.5
angle_min: -1.5708
angle_max: 1.5708
range_min: 0.3
range_max: 8.0